# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nD3aWRcZCUOk5GNrmfFN6btyTqCMc794
"""

#***********
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#***********
diabetes_df = pd.read_csv("diabetes.csv")

#***********
diabetes_df

#***********
x = diabetes_df[["BMI","Age"]] # This uses the colomns of BMI and Age
k = 2 # Sets the number of clusters in the scatter plot
clt = KMeans(n_clusters=k) 
clt.fit(x) # Fits the data
cluster_lables = clt.predict(x) # Creates the labels

#***********
colors = ["b","r","g","c","m","y","k"] # Colors
plt.figure(figsize=(16,10))

#***********
for i, row in diabetes_df.iterrows(): 
  curr_label = cluster_lables[i] # Sets the lables to datapoints
  curr_color = colors[curr_label] # Sets the color to datapoints
  plt.scatter(row["Age"],row["BMI"],c=curr_color, s=20)
  plt.text(row["Age"],row["BMI"],row["Outcome"],size=10)
plt.xlabel("AGE")
plt.ylabel("BMI")
plt.show()



